CREATE TABLE "books" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"author" varchar(255) NOT NULL,
	"isbn" varchar(17),
	"grade" bigint,
	"barcode" varchar(50),
	"published_year" integer,
	"publisher" varchar(255),
	"pages" integer,
	"language" varchar(50),
	"genre" varchar(100),
	"description" text,
	"price" numeric(10, 2),
	"cover_image_url" varchar(500),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "books_isbn_unique" UNIQUE("isbn"),
	CONSTRAINT "books_barcode_unique" UNIQUE("barcode")
);
--> statement-breakpoint
CREATE INDEX "author_idx" ON "books" USING btree ("author");--> statement-breakpoint
CREATE INDEX "genre_idx" ON "books" USING btree ("genre");--> statement-breakpoint
CREATE INDEX "grade_idx" ON "books" USING btree ("grade");--> statement-breakpoint
CREATE INDEX "published_year_idx" ON "books" USING btree ("published_year");